name: Hive Detokenization CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - 'hive/detokenization/**'
      - '.github/workflows/hive-detokenization-ci.yml'

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"
          cache: "maven"


      - name: Build & Test with Maven
        run: mvn -B package jacoco:report -f hive/detokenization/pom.xml -Dmaven.javadoc.skip=true

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: hive/detokenization/target/site/jacoco/jacoco.xml
          name: codecov-hive-detokenization
          fail_ci_if_error: true
          verbose: true

      - name: Upload Local Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-html
          path: hive/detokenization/target/site/jacoco/